version: '3.8'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    networks:
      - mongo-app-net
    command: >
      mongod --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    networks:
      - mongo-app-net
    command: >
      mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    networks:
      - mongo-app-net
    command: >
      mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo3_data:/data/db

  app:
    image: node:18
    container_name: app
    networks:
      - mongo-app-net
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    command: >
      sh -c "npm install && node index.js"
    depends_on:
      - mongo1

networks:
  mongo-app-net:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
